Copy directory structure recursive
dokku/dokku-copy-files-to-image pull request #2
Opened 2018-11-16 08:09 UTC by aivils

2018-11-21 20:26 UTC, josegonzalez commented on post-release-buildpack
> +    # docker kill $id > /dev/null 2>&1 || true
Why this?

2018-11-22 06:11 UTC, aivils commented on post-release-buildpack
> +    # docker kill $id > /dev/null 2>&1 || true
It looks pretty weird. I am not a docker expert. I cannot found similar code in the similar plugins. Can You explain for what is stop and kill?

2018-11-26 15:28 UTC, josegonzalez requested changes

2018-11-26 15:28 UTC, josegonzalez commented on post-release-buildpack
> +    # docker kill $id > /dev/null 2>&1 || true
It stops/kills the container dangling container that we created for the copy step: https://docs.docker.com/engine/reference/commandline/stop/

2018-11-26 15:28 UTC, josegonzalez commented on post-release-dockerfile
> +#!/usr/bin/env bash
I would remove this completely. If you're using a dockerfile for deploys, you should be shipping all the code that you need for the docker image within your repository. I'm not merging the code with this change, full-stop.

2018-11-27 06:59 UTC, aivils commented on post-release-dockerfile
> +#!/usr/bin/env bash
Okay, I don't need this plugin without Dockerfile.

2018-11-27 06:59 UTC, closed without merging

2018-11-27 07:38 UTC, aivils commented
Unfortunately I am not sure Dockerfile can access anything outside git repo provided by dokku. This way looks for me very powerful. It copies anything without weird rules. Yes my project have Dockerfile. Yes my project does not have private docker image.
As a result I cannot imagine simple way copy files from host's absolute path.